/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppWishlistRouteImport } from './routes/_authenticated.app.wishlist'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated.app.feed'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated.app.chat'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWishlistRoute =
  AuthenticatedAppWishlistRouteImport.update({
    id: '/app/wishlist',
    path: '/app/wishlist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/app/feed',
  path: '/app/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/wishlist': typeof AuthenticatedAppWishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/app/admin'
    | '/app/chat'
    | '/app/feed'
    | '/app/profile'
    | '/app/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/admin'
    | '/app/chat'
    | '/app/feed'
    | '/app/profile'
    | '/app/wishlist'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/onboarding'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/feed'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/wishlist': {
      id: '/_authenticated/app/wishlist'
      path: '/app/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AuthenticatedAppWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/feed': {
      id: '/_authenticated/app/feed'
      path: '/app/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppWishlistRoute: typeof AuthenticatedAppWishlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppWishlistRoute: AuthenticatedAppWishlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
